# Generated by Django 5.1 on 2024-10-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0003_remove_astronomyshow_show_theme_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'show_session'), name='unique_reservation_row_seat'),
        ),
    ]
